name: "Publish Emanote site"
on:
  push:
    branches:
      - main
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build emanote site 🔧
      run: |
        mkdir -p output 
        docker run -v $PWD:/data sridca/emanote emanote gen /data/output
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output/
        # cname: kb.haskell.org